/**
 * 선박 데이터 — 선박관리카드(hwpx) 기반 실제 제원
 *
 * 가격은 미확인 → null.
 * 사진·관리카드로 확인 안 되는 features는 제거.
 */

import type { Vessel } from "@/lib/supabase";

export const VESSEL_OVERRIDES: Record<
  string,
  Partial<Omit<Vessel, "vessel_images">>
> = {
  "suyeon-1": {
    title: "수연1호",
    vessel_type: "기선(강선)",
    year_built: 1983,
    length_m: 20.09,
    tonnage: 33,
    engine_power: "미쯔비시 750HP",
    capacity: 4,
    location: "인천 연안부두",
    description:
      "1983년 일본 본와조선 건조, 강선. 미쯔비시 주기관 탑재, 생활발전기 완비. 예항력 15.55톤(2,000톤 이상). 인천항 기반 근해 예인·화물 운송.",
    features: ["미쯔비시 주기관", "생활발전기", "경유필터", "오일필터"],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: true,
  },
  "suyeon-3": {
    title: "수연3호",
    vessel_type: "화물선",
    year_built: null,
    length_m: null,
    tonnage: null,
    engine_power: null,
    capacity: null,
    location: "인천",
    description: "수연선박 소속 화물선.",
    features: [],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: false,
  },
  "suyeon-5": {
    title: "수연5호",
    vessel_type: "기선(FRP)",
    year_built: 1995,
    length_m: 18,
    tonnage: 24,
    engine_power: null,
    capacity: null,
    location: "인천 연안부두",
    description:
      "1995년 경남 고성 세모조선 건조, FRP선. 선실, 조타실 완비.",
    features: ["선실", "조타실"],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: true,
  },
  "suyeon-6": {
    title: "수연6호",
    vessel_type: "기선(FRP)",
    year_built: 2010,
    length_m: 14.4,
    tonnage: 14,
    engine_power: null,
    capacity: 16,
    location: "인천 연안부두",
    description:
      "2010년 전남 여수 신우조선 건조, FRP선. 환경정화 활동 참여 이력. 선원실, 조타실 완비.",
    features: ["선원실", "조타실"],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: true,
  },
  "suyeon-9": {
    title: "수연9호",
    vessel_type: "레저선",
    year_built: null,
    length_m: null,
    tonnage: null,
    engine_power: "야마하 250마력",
    capacity: null,
    location: "인천",
    description: "야마하 250마력 선외기 탑재.",
    features: ["야마하 250마력 선외기"],
    rent_price_per_day: null,
    sale_price: null,
    type: "rent",
    is_featured: false,
  },
  sinseong: {
    title: "신성호",
    vessel_type: "기타선(FRP)",
    year_built: 1989,
    length_m: 13.84,
    tonnage: 10,
    engine_power: null,
    capacity: 12,
    location: "인천 연안부두",
    description:
      "1989년 전남 고흥 형제조선 건조, FRP선. 도선(임시승선10명, 선원2명). 선실, 조타실 완비.",
    features: ["선실", "조타실"],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: true,
  },
  youngjin: {
    title: "영진호",
    vessel_type: "기타선(통선)(FRP)",
    year_built: 1997,
    length_m: 14.8,
    tonnage: 12,
    engine_power: null,
    capacity: 10,
    location: "인천 연안부두",
    description:
      "1997년 전남 고흥 남해FRP조선소 건조. 통선(여객8명, 선원2명). 판매 전용.",
    features: [],
    rent_price_per_day: null,
    sale_price: null,
    type: "sale",
    is_featured: false,
  },
  "jinyang-2": {
    title: "진양2호",
    vessel_type: "기타선(통선)(강선)",
    year_built: 1984,
    length_m: 12.1,
    tonnage: 7.98,
    engine_power: null,
    capacity: 11,
    location: "인천 연안부두",
    description:
      "1984년 일본 장포조선 건조, 강선. 통선(여객10명, 선원1명). 항해 실적 다수.",
    features: ["선실"],
    rent_price_per_day: null,
    sale_price: null,
    type: "both",
    is_featured: true,
  },
};
